# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb487813f0e15f450ef4f508df815dc1ad92594a7b82154a6bfe8ab583f9f0f3e210b317bd09dc947bb4e672b7779314977c1f9570b130d54ae53522571c953

test:
  secret_key_base: 58f17ebc1fd6082c00b3007909576862edb4de5a608460afe984810ee2d5b9368f553943b03320928c5f3102fa327feda75791c28266bec35c687042e6f94362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
